class_name Enums

enum EXCEPTIONS{ILLEGAL_COMMAND, ILLEGAL_ARGUMENTS, MISSING_ARGUMENTS, EMPTY, OUT_OF_RANGE, UNKNOWN_TYPE, UNKNOWN_REFERENCE, TILE_COLLIDES, DEAD_ENTITY}

enum COLLIDER{ENEMY, ALLY, PART, MAP}

enum STATUS{IDLE, MOVING, ATTACKING, DEAD}

enum ACTIONS{PAVILION, MOVE, NONE}