class_name Enums

enum EXCEPTIONS{ILLEGAL_COMMAND, ILLEGAL_ARGUMENTS, MISSING_ARGUMENTS, EMPTY, OUT_OF_RANGE, UNKNOWN_TYPE, UNKNOWN_REFERENCE}

enum COLLIDER{ENEMY, ALLY, PART, MAP}

enum STATUS{IDLE, MOVING, ATTACKING}